apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: env
        value: "dev"
  templates:
    - name: main
      dag:
        tasks:
          - name: extract
            template: run
            arguments:
              parameters:
                - name: message
                  value: "extracting data [{{workflow.parameters.env}}]"
          - name: transform
            template: run
            dependencies: [extract]
            arguments:
              parameters:
                - name: message
                  value: "transforming data [{{workflow.parameters.env}}]"
          - name: load
            template: run
            dependencies: [transform]
            arguments:
              parameters:
                - name: message
                  value: "loading data [{{workflow.parameters.env}}]"
    - name: run
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.18
        command: [sh, -c]
        args: ["echo '{{inputs.parameters.message}}' && sleep 3"]